#!/bin/sh -e
set -e

#DEBHELPER#

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    # remove background alternatives
    for background in \
          anger-wallpaper_1280x1024.svg \
          anger-wallpaper_1600x1200.svg \
          anger-wallpaper_1920x1080.svg \
          anger-wallpaper_1920x1200.svg \
          anger-wallpaper_2560x1080.svg \
          eta-wallpaper_1920x1080.svg \
          gray-wallpaper_1280x1024.svg \
          gray-wallpaper_1600x1200.svg \
          gray-wallpaper_1920x1080.svg \
          gray-wallpaper_1920x1200.svg \
          ; do
        update-alternatives --remove desktop-background /usr/share/images/desktop-base/$background
    done
    # remove desktop-background.xml alternatives
    for desktopbackground in \
          anger.xml \
          eta.xml \
          gray.xml \
          ; do
        update-alternatives --remove desktop-background.xml /usr/share/images/desktop-base/$desktopbackground
    done

    # remove splash alternatives
    for splash in \
          pardus-splash.png \
          ; do
        update-alternatives --remove desktop-splash /usr/share/images/desktop-base/$splash
    done

    # remove grub alternatives
    for background in \
          pardus-grub.png \
          pardus-grub-1920x1080.png \
          ; do
        update-alternatives --remove desktop-grub /usr/share/images/desktop-base/$background
    done
fi
